### ISSUE TITLE
Outdated package errors with python 3.10 (macOS)

### ISSUE THREAD

**Issue by LukaVerhoeven** [truefoundry/cognita#147]
I am struggling with the installation process and I receive following error:

Command:
`cognita % python -m local.ingest`

Error:
````
Traceback (most recent call last):
  File "/Users/directory/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/directory/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/directory/Digital skill academy/cognita/local/ingest.py", line 3, in <module>
    from backend.settings import Settings
  File "/Users/directory/Digital skill academy/cognita/backend/settings.py", line 5, in <module>
    from pydantic import BaseSettings
  File "/Users/directory/miniconda3/lib/python3.10/site-packages/pydantic/__init__.py", line 380, in __getattr__
    return _getattr_migration(attr_name)
  File "/Users/directory/miniconda3/lib/python3.10/site-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.7/u/import-error
````

System:
MacOS (M3)

**Comment by LukaVerhoeven** [comment]
Changed python to 3.11 and seems to be working now.
(I do get other erros now)
