### ISSUE TITLE
CrossEncoder of Sentence Transformers uses best device type available on machine leading to error 

### ISSUE THREAD

**Issue by ghost** [truefoundry/cognita#172]
Hi Team!!

While I was trying to explore Cognita, I have found an error trying to run the retrieval augmented generation locally using ./local/run.py
The machine I am using is MacBook Air, Apple M1 chip, macOS 13.1 (22C65) which has mps

As the CrossEncoder from sentence_transformers library uses below function which returns 'mps' on my machine
```
def get_device_name() -> Literal["mps", "cuda", "npu", "hpu", "cpu"]:
    if torch.cuda.is_available():
        return "cuda"
    elif torch.backends.mps.is_available():
        return "mps"
    elif is_torch_npu_available():
        return "npu"
    elif importlib.util.find_spec("habana_frameworks") is not None:
        import habana_frameworks.torch.hpu as hthpu

        if hthpu.is_available():
            return "hpu"
    return "cpu"
```
I am encountering this error
```
ERROR:    2024-05-28 01:23:19,041 - controller:answer:336 - Operation 'sign_out_mps()' does not support input type 'int64' in MPS backend.
Traceback (most recent call last):
  File "/Users/malyala/Desktop/cognita/backend/modules/query_controllers/example/controller.py", line 312, in answer
    outputs = await rag_chain_with_source.ainvoke(request.query)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2109, in ainvoke
    input = await step.ainvoke(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2739, in ainvoke
    results = await asyncio.gather(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 157, in ainvoke
    return await self.aget_relevant_documents(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 300, in aget_relevant_documents
    raise e
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 293, in aget_relevant_documents
    result = await self._aget_relevant_documents(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain/retrievers/multi_query.py", line 104, in _aget_relevant_documents
    documents = await self.aretrieve_documents(queries, run_manager)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain/retrievers/multi_query.py", line 137, in aretrieve_documents
    document_lists = await asyncio.gather(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 300, in aget_relevant_documents
    raise e
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 293, in aget_relevant_documents
    result = await self._aget_relevant_documents(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain/retrievers/contextual_compression.py", line 74, in _aget_relevant_documents
    compressed_docs = await self.base_compressor.acompress_documents(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain/retrievers/document_compressors/base.py", line 31, in acompress_documents
    return await run_in_executor(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 493, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/malyala/Desktop/cognita/backend/modules/reranker/mxbai_reranker.py", line 27, in compress_documents
    reranked_docs = model.rank(query, docs, return_documents=True, top_k=self.top_k)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 419, in rank
    scores = self.predict(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 332, in predict
    model_predictions = self.model(**features, return_dict=True)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 1296, in forward
    outputs = self.deberta(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 1066, in forward
    encoder_outputs = self.encoder(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 484, in forward
    relative_pos = self.get_rel_pos(hidden_states, query_states, relative_pos)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 460, in get_rel_pos
    relative_pos = build_relative_position(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 583, in build_relative_position
    rel_pos_ids = make_log_bucket_position(rel_pos_ids, bucket_size, max_position)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 546, in make_log_bucket_position
    sign = torch.sign(relative_pos)
TypeError: Operation 'sign_out_mps()' does not support input type 'int64' in MPS backend.
Traceback (most recent call last):
  File "/Users/malyala/Desktop/cognita/backend/modules/query_controllers/example/controller.py", line 312, in answer
    outputs = await rag_chain_with_source.ainvoke(request.query)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2109, in ainvoke
    input = await step.ainvoke(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2739, in ainvoke
    results = await asyncio.gather(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 157, in ainvoke
    return await self.aget_relevant_documents(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 300, in aget_relevant_documents
    raise e
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 293, in aget_relevant_documents
    result = await self._aget_relevant_documents(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain/retrievers/multi_query.py", line 104, in _aget_relevant_documents
    documents = await self.aretrieve_documents(queries, run_manager)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain/retrievers/multi_query.py", line 137, in aretrieve_documents
    document_lists = await asyncio.gather(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 300, in aget_relevant_documents
    raise e
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/retrievers.py", line 293, in aget_relevant_documents
    result = await self._aget_relevant_documents(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain/retrievers/contextual_compression.py", line 74, in _aget_relevant_documents
    compressed_docs = await self.base_compressor.acompress_documents(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain/retrievers/document_compressors/base.py", line 31, in acompress_documents
    return await run_in_executor(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 493, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/malyala/Desktop/cognita/backend/modules/reranker/mxbai_reranker.py", line 27, in compress_documents
    reranked_docs = model.rank(query, docs, return_documents=True, top_k=self.top_k)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 419, in rank
    scores = self.predict(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 332, in predict
    model_predictions = self.model(**features, return_dict=True)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 1296, in forward
    outputs = self.deberta(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 1066, in forward
    encoder_outputs = self.encoder(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 484, in forward
    relative_pos = self.get_rel_pos(hidden_states, query_states, relative_pos)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 460, in get_rel_pos
    relative_pos = build_relative_position(
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 583, in build_relative_position
    rel_pos_ids = make_log_bucket_position(rel_pos_ids, bucket_size, max_position)
  File "/Users/malyala/Desktop/env/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 546, in make_log_bucket_position
    sign = torch.sign(relative_pos)
TypeError: Operation 'sign_out_mps()' does not support input type 'int64' in MPS backend.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/malyala/Desktop/cognita/./local/run.py", line 41, in <module>
    answer = asyncio.run(controller.answer(ExampleQueryInput(**request)))
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/malyala/Desktop/cognita/backend/modules/query_controllers/example/controller.py", line 337, in answer
    raise HTTPException(status_code=500, detail=str(exp))
fastapi.exceptions.HTTPException
```

Looks like there are some operations(torch.sign) in deberta_v2 model which do not support on some data types (int64). Shouldn't there be a env variable to handle device type to use while running locally or deploying RAG on any system?

**Comment by chiragjn** [comment]
Thanks for reporting this
We have added fallback to cpu if cuda is not available

Later down the line we will add device control using argument or env variable as you suggested.
Keeping this issue open to track
