### ISSUE TITLE
Error: P1001: Can't reach database server at `host.docker.internal`:`5432`

### ISSUE THREAD

**Issue by magick93** [truefoundry/cognita#244]
Hello

I'm getting the following error when attempting to start using `docker compose --env-file compose.env up`:

```
cognita-backend   | Installing Prisma CLI
cognita-backend   |  * Install prebuilt node (22.3.0) ..... done.
cognita-backend   | Prisma schema loaded from backend/database/schema.prisma
cognita-backend   | Datasource "db": PostgreSQL database "cognita-config", schema "public" at "host.docker.internal:5432"
cognita-backend   | 
cognita-backend   | Error: P1001: Can't reach database server at `host.docker.internal`:`5432`
cognita-backend   | 
cognita-backend   | Please make sure your database server is running at `host.docker.internal`:`5432`.
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container cognita-backend is unhealthy
```

# Versions

- Docker Compose version v2.27.1

Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.44 (downgraded from 1.45)
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:28:57 2024
 OS/Arch:           linux/amd64
 Context:           rootless

Server: Docker Engine - Community
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:03 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.0.0
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/1000/dockerd-rootless
 slirp4netns:
  Version:          1.1.8
  GitCommit:        unknown

OS - Ubuntu 24.04 LTS

**Comment by magick93** [comment]
If I modify the `compose.env` file to `DOCKER_HOST=db.cognita_cognita-docker` I'm able to pass the above error. 

However, I then get:

```
[+] Running 4/4
 ✔ Container cognita-postgres  Running                                                                                                                   0.0s 
 ✔ Container qdrant            Running                                                                                                                   0.0s 
 ✔ Container cognita-backend   Recreated                                                                                                                 1.5s 
 ✔ Container cognita-frontend  Created                                                                                                                   0.3s 
Attaching to cognita-backend, cognita-frontend, cognita-postgres, qdrant
cognita-backend   | Installing Prisma CLI
cognita-backend   |  * Install prebuilt node (22.3.0) ..... done.
cognita-backend   | Prisma schema loaded from backend/database/schema.prisma
cognita-backend   | Datasource "db": PostgreSQL database "cognita-config", schema "public" at "db.cognita_cognita-docker:5432"
cognita-backend   | 
cognita-backend   | The database is already in sync with the Prisma schema.
cognita-backend   | 
✔ Generated Prisma Client Python (v0.13.1) to ./../virtualenvs/venv/lib/python3.
cognita-backend   | 11/site-packages/prisma in 225ms
cognita-backend   | 
cognita-backend   | INFO:     Will watch for changes in these directories: ['/app']
cognita-backend   | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
cognita-backend   | INFO:     Started reloader process [91] using StatReload
cognita-backend   | Process SpawnProcess-1:
cognita-backend   | Traceback (most recent call last):
cognita-backend   |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
cognita-backend   |     self.run()
cognita-backend   |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
cognita-backend   |     self._target(*self._args, **self._kwargs)
cognita-backend   |   File "/virtualenvs/venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
cognita-backend   |     target(sockets=sockets)
cognita-backend   |   File "/virtualenvs/venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
cognita-backend   |     return asyncio.run(self.serve(sockets=sockets))
cognita-backend   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognita-backend   |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
cognita-backend   |     return runner.run(main)
cognita-backend   |            ^^^^^^^^^^^^^^^^
cognita-backend   |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
cognita-backend   |     return self._loop.run_until_complete(task)
cognita-backend   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognita-backend   |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
cognita-backend   |     return future.result()
cognita-backend   |            ^^^^^^^^^^^^^^^
cognita-backend   |   File "/virtualenvs/venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
cognita-backend   |     config.load()
cognita-backend   |   File "/virtualenvs/venv/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
cognita-backend   |     self.loaded_app = import_from_string(self.app)
cognita-backend   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognita-backend   |   File "/virtualenvs/venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
cognita-backend   |     module = importlib.import_module(module_str)
cognita-backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognita-backend   |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
cognita-backend   |     return _bootstrap._gcd_import(name[level:], package, level)
cognita-backend   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognita-backend   |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
cognita-backend   |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
cognita-backend   |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
cognita-backend   |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
cognita-backend   |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
cognita-backend   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
cognita-backend   |   File "/app/backend/server/app.py", line 5, in <module>
cognita-backend   |     from backend.modules.query_controllers.query_controller import QUERY_CONTROLLER_REGISTRY
cognita-backend   |   File "/app/backend/modules/query_controllers/__init__.py", line 1, in <module>
cognita-backend   |     from backend.modules.query_controllers.example.controller import BasicRAGQueryController
cognita-backend   |   File "/app/backend/modules/query_controllers/example/controller.py", line 15, in <module>
cognita-backend   |     from backend.modules.model_gateway.model_gateway import model_gateway
cognita-backend   |   File "/app/backend/modules/model_gateway/model_gateway.py", line 85, in <module>
cognita-backend   |     model_gateway = ModelGateway()
cognita-backend   |                     ^^^^^^^^^^^^^^
cognita-backend   |   File "/app/backend/modules/model_gateway/model_gateway.py", line 15, in __init__
cognita-backend   |     with open("./models_config.json") as f:
cognita-backend   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognita-backend   | FileNotFoundError: [Errno 2] No such file or directory: './models_config.json'
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container cognita-backend is unhealthy
```

**Comment by S1LV3RJ1NX** [comment]
The readme is in process, you need to create a `models_config.json` from `models_config.sample.json` providing the necessary API keys. 

Also, how did you arrive at `DOCKER_HOST` url? actually the reason for me keeping it there was only that, I was not able to access the db service.

**Comment by magick93** [comment]
> how did you arrive at DOCKER_HOST url? 

From inspecting any of the running contains you can see the name of the network, and the service name is what is specified in the docker compose file.

**Comment by S1LV3RJ1NX** [comment]
Can you try DOCKER_HOST=db?

**Comment by magick93** [comment]
Yes I tried that but it didnt work.

**Comment by S1LV3RJ1NX** [comment]
DOCKER_HOST as db works for me...what's your os?

**Comment by magick93** [comment]
Ubuntu 24.04

**Comment by S1LV3RJ1NX** [comment]
I suppose if you could give container ip as host it should work in linux

**Comment by S1LV3RJ1NX** [comment]
@magick93, can you now check with the latest main.

**Comment by chiragjn** [comment]
Just adding steps as we have changed models_config now to be a yaml spec

```
git pull origin main
cp models_config.sample.yaml models_config.yaml
docker compose --env-file compose.env --profile '*' up -d
```

**Comment by chiragjn** [comment]
I am closing this, but please feel free to re-open if things don't work out for you on lastest main :)
