### ISSUE TITLE
Circular import with types.py

### ISSUE THREAD

**Issue by gegedenice** [truefoundry/cognita#280]
When building image with source code (main branch) and docker compose, the backend container is healthy but logs this error

Traceback (most recent call last):
2024-07-19 15:26:28   File "<string>", line 1, in <module>
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/multiprocessing/__init__.py", line 16, in <module>
2024-07-19 15:26:28 Traceback (most recent call last):
2024-07-19 15:26:28   File "<string>", line 1, in <module>
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/multiprocessing/__init__.py", line 16, in <module>
2024-07-19 15:26:28     from . import context
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/multiprocessing/context.py", line 3, in <module>
2024-07-19 15:26:28     from . import context
2024-07-19 15:26:28     import threading
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/threading.py", line 6, in <module>
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/multiprocessing/context.py", line 3, in <module>
2024-07-19 15:26:28     import functools
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/functools.py", line 22, in <module>
2024-07-19 15:26:28     import threading
2024-07-19 15:26:28     from types import GenericAlias
2024-07-19 15:26:28   File "/app/types.py", line 1, in <module>
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/threading.py", line 6, in <module>
2024-07-19 15:26:28     import functools
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/functools.py", line 22, in <module>
2024-07-19 15:26:28     from types import GenericAlias
2024-07-19 15:26:28     import enum
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/enum.py", line 3, in <module>
2024-07-19 15:26:28   File "/app/types.py", line 1, in <module>
2024-07-19 15:26:28     from types import MappingProxyType, DynamicClassAttribute
2024-07-19 15:26:28 ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/app/types.py)
2024-07-19 15:26:28     import enum
2024-07-19 15:26:28   File "/usr/local/lib/python3.11/enum.py", line 3, in <module>
2024-07-19 15:26:28     from types import MappingProxyType, DynamicClassAttribute
2024-07-19 15:26:28 ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/app/types.py)

**Comment by gegedenice** [comment]
Thank you !

**Comment by agutgutia1991** [comment]
Thanks a lot Geraline and gmconte.
We will also get this fixed at our end. If okay with you to share your
emails, i will add you to an internal evangelist group so we can further
improve Cognita. Kindly let me know.

**Comment by S1LV3RJ1NX** [comment]
@gegedenice can u check if you have installed your requirements correctly? I am not able to reproduce this on my end.
