### ISSUE TITLE
openai.APIConnectionError: Connection error

### ISSUE THREAD

**Issue by a2652232** [truefoundry/cognita#351]
Hello,

I am trying to build the local environment with OpenAI API Key. I have updated the models_config.yaml and compose.env. But when I started to run the docker, the following long error messages pop up, and most of them are relevant to the connect error. Could anyone help me with this? Thank you!

2024-09-24 11:12:13 httpx.ConnectError: [Errno -2] Name or service not known
2024-09-24 11:12:13 
2024-09-24 11:12:13 The above exception was the direct cause of the following exception:
2024-09-24 11:12:13 
2024-09-24 11:12:13 Traceback (most recent call last):
2024-09-24 11:12:13   File "/app/backend/utils.py", line 108, in _async_to_sync
2024-09-24 11:12:13     result = loop.run_until_complete(fn(*args, **kwargs))
2024-09-24 11:12:13              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
2024-09-24 11:12:13     return future.result()
2024-09-24 11:12:13            ^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/app/backend/indexer/indexer.py", line 107, in sync_data_source_to_collection
2024-09-24 11:12:13     raise e
2024-09-24 11:12:13   File "/app/backend/indexer/indexer.py", line 97, in sync_data_source_to_collection
2024-09-24 11:12:13     await _sync_data_source_to_collection(
2024-09-24 11:12:13   File "/app/backend/indexer/indexer.py", line 183, in _sync_data_source_to_collection
2024-09-24 11:12:13 [PID:224/SpawnProcess-1:1][140151636339584/MainThread] DEBUG:    2024-09-24 01:12:13,804 - qdrant:list_data_point_vectors:194 - [Qdrant] Listing all data point vectors for collection safetyweb
2024-09-24 11:12:13 [PID:224/SpawnProcess-1:1][140151636339584/MainThread] DEBUG:    2024-09-24 01:12:13,863 - qdrant:list_data_point_vectors:242 - [Qdrant] Listing 768 data point vectors for collection safetyweb
2024-09-24 11:12:13 [PID:224/SpawnProcess-1:1][140151636339584/MainThread] INFO:    2024-09-24 01:12:13,864 - indexer:sync_data_source_to_collection:81 - Total existing data point vectors in collection safetyweb: 768
2024-09-24 11:12:13 [PID:224/SpawnProcess-1:1][140151636339584/MainThread] INFO:    2024-09-24 01:12:13,869 - indexer:_sync_data_source_to_collection:160 - Loading data from data source
2024-09-24 11:16:00 Prisma schema loaded from backend/database/schema.prisma
2024-09-24 11:16:00 Datasource "db": PostgreSQL database "cognita-config", schema "public" at "cognita-db:5432"
2024-09-24 11:16:00 
2024-09-24 11:16:00 The database is already in sync with the Prisma schema.
2024-09-24 11:16:00 
✔ Generated Prisma Client Python (v0.13.1) to ./../virtualenvs/venv/lib/python3.
2024-09-24 11:16:01 11/site-packages/prisma in 191ms
2024-09-24 11:16:01 
2024-09-24 11:16:06 [PID:79/SpawnProcess-1][139679355116416/MainThread] INFO:    2024-09-24 01:16:06,237 - model_gateway:__init__:22 - Loading models config from /app/./models_config.yaml
2024-09-24 11:12:13     raise e
2024-09-24 11:12:13   File "/app/backend/indexer/indexer.py", line 172, in _sync_data_source_to_collection
2024-09-24 11:12:13     await ingest_data_points(
2024-09-24 11:12:13   File "/app/backend/indexer/indexer.py", line 295, in ingest_data_points
2024-09-24 11:12:13     VECTOR_STORE_CLIENT.upsert_documents(
2024-09-24 11:12:13   File "/app/backend/modules/vector_db/qdrant.py", line 144, in upsert_documents
2024-09-24 11:12:13     ).add_documents(documents=documents)
2024-09-24 11:12:13       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 138, in add_documents
2024-09-24 11:12:13     return self.add_texts(texts, metadatas, **kwargs)
2024-09-24 11:12:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/langchain_community/vectorstores/qdrant.py", line 187, in add_texts
2024-09-24 11:12:13     for batch_ids, points in self._generate_rest_batches(
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/langchain_community/vectorstores/qdrant.py", line 2097, in _generate_rest_batches
2024-09-24 11:12:13     batch_embeddings = self._embed_texts(batch_texts)
2024-09-24 11:12:13                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/langchain_community/vectorstores/qdrant.py", line 2037, in _embed_texts
2024-09-24 11:12:13     embeddings = self.embeddings.embed_documents(list(texts))
2024-09-24 11:12:13                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 477, in embed_documents
2024-09-24 11:12:13     response = self.client.create(
2024-09-24 11:12:13                ^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/openai/resources/embeddings.py", line 114, in create
2024-09-24 11:12:13     return self._post(
2024-09-24 11:12:13            ^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1250, in post
2024-09-24 11:12:13     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
2024-09-24 11:12:13                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/openai/_base_client.py", line 931, in request
2024-09-24 11:12:13     return self._request(
2024-09-24 11:12:13            ^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/openai/_base_client.py", line 986, in _request
2024-09-24 11:12:13     return self._retry_request(
2024-09-24 11:12:13            ^^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in _retry_request
2024-09-24 11:12:13     return self._request(
2024-09-24 11:12:13            ^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/openai/_base_client.py", line 986, in _request
2024-09-24 11:12:13     return self._retry_request(
2024-09-24 11:12:13            ^^^^^^^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in _retry_request
2024-09-24 11:12:13     return self._request(
2024-09-24 11:12:13            ^^^^^^^^^^^^^^
2024-09-24 11:12:13   File "/virtualenvs/venv/lib/python3.11/site-packages/openai/_base_client.py", line 996, in _request
2024-09-24 11:12:13     raise APIConnectionError(request=request) from err
2024-09-24 11:12:13 openai.APIConnectionError: Connection error.

**Comment by a2652232** [comment]
I think I have solved this by myself. Here is the solution if anyone else encountered this:
1. When you uncommented the openai part in the models_config.yaml, an indent will be missing and result in Parsing Error.
2. The entire docker needs to be re-setup using docker terminal after updating the environment variable in compose.env.

Now this issue can be close.
